
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import dev.task4233.playground.controlFlowGraph.CFG;

import static org.junit.Assert.*;

public class CFGTest {
    @Test
    public void testCFGIsCorrectlyGenerated() {
        CFG cfg = new CFG();
        assertNotNull(cfg);

        // commented out for memory
        // cfg.constructCFG();

        // File file = new File(CFG.allApisFilePath);
        // assertTrue(file.getAbsolutePath(), file.exists());

        // file = new File(CFG.apiFrequenciesFilePath);
        // assertTrue(file.getAbsolutePath(), file.exists());

        // file = new File(CFG.apiSequencesFilePath);
        // assertTrue(file.getAbsolutePath(), file.exists());

        // file = new File(CFG.apiSequenceIndicesFilePath);
        // assertTrue(file.getAbsolutePath(), file.exists());
    }
}
